term.clear()
term.setCursorPos(10,1)
term.setTextColor(colors.orange)
print("BANK CLIENT")
term.setCursorPos(1,3)
rednet.open("top")
write("Command: ")
local input = read()
rednet.send(2, input, "BANK:4471")
local senderId, message, protocol = rednet.receive("BANK:4471")
print(message)